# This is the config file only for the onepennymedia theme.

blog_title: One Penny
blog_description: A web media reporting about web/app startups in Hangzhou.
subscribe:
  links:
    'rss': 'http://feeds.feedburner.com/OnePennyMedia'
    'email': 'mailto:shaoshing@me.com'
    'twitter': 'http://twitter.com/shaoshing'
footer:
  links:
    'About': '/pages/about'
    'Contact': '/pages/contact'
    'One Penny Entrepreneur EN': 'http://www.onepennyentrepreneur.com'
    'CN': 'https://www.yifency.com'
mobile_navigation: # Navigation displayed under the log for small screens, like iPhone.
  links:
    'Home': '/'
    'Archives': '/archives'
    'Categories': '/categories'
    'Tags': '/tags'
